Vagrant.configure(2) do |config|
  config.vm.box      = 'ubuntu/trusty64'

  config.vm.network :private_network, ip: '192.168.50.50'
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.synced_folder "./..", "/psycho-admin", nfs: true, mount_options: ['nolock,vers=3,udp,noatime,actimeo=1']
  config.ssh.forward_agent = true
  config.vm.hostname       = 'psycho-admin'

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'psycho-admin'
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--cpus", 4]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.provision :shell, privileged: false, inline: 'echo "cd /psycho-admin" >> /home/vagrant/.bashrc'
  config.vm.provision :shell, path: 'bootstrap.sh', keep_color: true
  config.vm.provision :shell, path: 'rbenv_install.sh', privileged: false, keep_color: true
end
